
foreground                      #ccc
background                      #000
selection_background            #fff

cursor                          #ff0

color0 #333
color8 #666

color1 #e00
color9 #f88

color2  #0a0
color10 #0f0

color3  #ff0
color11 #ffa

color4  #44f
color12 #aaf

color5  #a0a
color13 #f0f

color6  #0aa
color14 #0ff

color7  #ccc
color15 #fff
