
# kitty list-fonts

font_size                   20
# font_family                 MesloLGSDZ Nerd Font Mono
# font_family                 JetBrainsMono Nerd Font Mono
# font_family                 Lilex Nerd Font Mono
font_family                 TwilioSansM Nerd Font
italic_font                 Twilio Sans Mono Semibold Italic
bold_font                   Twilio Sans Mono Extrabold
bold_italic_font            Twilio Sans Mono Extrabold Italic
# bold_font                   JetBrainsMono Nerd Font Mono Bold
# bold_italic_font            Maple Mono NF Bold
# bold_italic_font            MesloLGSDZ Nerd Font Mono
# italic_font                 MesloLGSDZ Nerd Font Mono
# italic_font               Maple Mono NF Light
# bold_font                 GeistMono Nerd Font Mono
# bold_font                 TwilioSansM Nerd Font
# bold_font                 MonaspiceNe Nerd Font Mono
                            
shell                       /opt/homebrew/bin/fish

initial_window_width        95c
initial_window_height       45c
resize_in_steps             no
remember_window_size        yes
draw_minimal_borders        yes
window_margin_width         0
window_padding_width        0
window_border_width         0
resize_debounce_time        0.0 0.0
scrollback_lines            100000                            

tab_bar_edge                top
tab_bar_style               separator
tab_separator               ''
tab_powerline_style         round
tab_activity_symbol         ''
tab_bar_margin_width        0.0
tab_bar_margin_height       0.0 0.0
tab_bar_align               center
active_tab_foreground       #fff
active_tab_background       #44a
active_tab_font_style       bold-italic
inactive_tab_font_style     italic
inactive_tab_foreground     #999
inactive_tab_background     #333
tab_bar_background          #222

tab_title_template          "{fmt.fg._333}{fmt.bg._222}{fmt.fg.tab}{fmt.bg.tab}{title.split('/')[-1]}{fmt.fg._333}{fmt.bg._222}"
active_tab_title_template   "{fmt.fg._44a}{fmt.bg._222}{fmt.fg.tab}{fmt.bg.tab}{title.split('/')[-1]}{fmt.fg._44a}{fmt.bg._222}"

map cmd+r
map cmd+c
map cmd+v
map cmd+m
map cmd+enter
map kitty_mod+1
map kitty_mod+2
map kitty_mod+3
map cmd+1
map cmd+2
map cmd+3
map cmd+shift+d
map shift+cmd+d

map alt+c copy_to_clipboard  
map alt+v paste_from_clipboard
map alt+s kitten kitty_grab/grab.py

map kitty_mod+w close_other_tabs_in_os_window

mouse_map shift+left press grabbed discard_event

copy_on_select yes

include current-theme.conf