# Open directories
protocol file
mime inode/directory
action launch --type=os-window --hold --cwd -- $FILE_PATH

# Open text files without fragments in the editor
protocol file
mime text/*
action launch --type=os-window --hold -- /Users/kodi/s/kakao/kakao.app/bin/ked -- $FILE_PATH

# Open image files with icat
protocol file
mime image/*
action launch --type=os-window --hold kitten icat --hold -- $FILE_PATH
