
protocol file
ext kode,noon,json,js,log,txt,md
action launch --copy-env --cwd=current --hold --type=tab /Users/kodi/.local/share/nvm/v23.8.0/bin/node /Users/kodi/s/kakao/kakao.app/js/ked/ked.js ${FILE_PATH}

protocol file
mime text/*
action launch --copy-env --cwd=current --hold --type=tab /Users/kodi/.local/share/nvm/v23.8.0/bin/node /Users/kodi/s/kakao/kakao.app/bin/ked ${FILE_PATH}

protocol file
ext toml
action launch --copy-env --cwd=current --hold --type=tab /opt/homebrew/bin/fish -c /Users/kodi/s/kakao/kakao.app/bin/ked ${FILE_PATH}

protocol file
mime image/*
action launch --type=tab kitten icat --hold -- ${FILE_PATH}