set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

set noswapfile
set nocompatible
set term=ansi
set t_ku=[A
set t_kd=[B
set t_kl=[D
set t_kr=[C
