format = """
[](fg:#444444 bg:#333333)\
$directory\
[](fg:#444444 bg:#333333)\
$git_status\
[ ](fg:#333333 bg:#222222)\
[ ](fg:#222222)\
"""

[directory]
style = "fg:#aaaaff bg:#444444"
repo_root_style = "fg:#ff88aa bg:#444444"
before_repo_root_style = "fg:#aaaaff bg:#444444"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"  
truncate_to_repo = false
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)'

[directory.substitutions]
"~/shell" = " "
"~/s" = "⚙ "
"~/Documents" = " "
"~/Downloads" = " "
"~/Pictures" = " "
"~/Music" = " "
"~" = ""

[nodejs]
style = "bg:#222222"
format = '[[ ($version)](fg:#769ff0 bg:#222222)]($style)'
      
[git_status]
style = 'fg:#666666 bg:#333333'  
format = '[$modified]($style)'
modified = " ⚙"
