// Generated by CoffeeScript 1.8.0
(function() {
  var BG, BW, bold, colors, fg, fw, log, p, path, reset, s, _i, _len, _ref, _s;

  log = console.log;

  colors = require('ansi-256-colors');

  _s = require('underscore.string');

  bold = '\x1b[1m';

  reset = colors.reset;

  fg = colors.fg.getRgb;

  BG = colors.bg.getRgb;

  fw = function(i) {
    return colors.fg.grayscale[i];
  };

  BW = function(i) {
    return colors.bg.grayscale[i];
  };

  path = process.argv[2];

  if (_s.startsWith(path, process.env.HOME)) {
    path = "~" + path.substr(process.env.HOME.length);
  }

  if (path == null) {
    path = '.';
  }

  s = "  ";

  if (path === '/') {
    s += fg(4, 3, 0) + '/';
  } else {
    _ref = path.split('/');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      if (p) {
        if (p[0] !== "~") {
          s += fg(1, 1, 1) + '/';
        }
        s += fg(4, 3, 0) + p;
      }
    }
  }

  log(BW(1) + bold + s + "  " + reset);

}).call(this);
