// Generated by CoffeeScript 1.9.2
(function() {
  var BG, BW, _s, bold, colors, fg, fw, j, len, log, p, path, ref, reset, s;

  log = console.log;

  colors = require('ansi-256-colors');

  _s = require('underscore.string');

  bold = '\x1b[1m';

  reset = colors.reset;

  fg = colors.fg.getRgb;

  BG = colors.bg.getRgb;

  fw = function(i) {
    return colors.fg.grayscale[i];
  };

  BW = function(i) {
    return colors.bg.grayscale[i];
  };

  path = process.argv[2];

  if (_s.startsWith(path, process.env.HOME)) {
    path = "~" + path.substr(process.env.HOME.length);
  }

  s = "  ";

  if (path === '/') {
    s += fg(4, 3, 0) + '/';
  } else {
    ref = path.split('/');
    for (j = 0, len = ref.length; j < len; j++) {
      p = ref[j];
      if (p) {
        if (p[0] !== "~") {
          s += fg(1, 1, 1) + '/';
        }
        s += fg(4, 3, 0) + p;
      }
    }
  }

  log(BW(1) + bold + s + "  " + reset);

}).call(this);
